name: Dependency Vulnerability Scan

on:
    #workflow_call:
     workflow_dispatch   
jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "bankapp"
          path: "."
          format: "HTML"

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: reports/dependency-check-report.html