name: devsecops pipeline
on: 
   workflow_dispatch: 

jobs:
    #CI
    code-quality_scan:
        uses: ./.github/workflows/code_quality_check.yml
    secrets_scan:
        uses: ./.github/workflows/secret_scan.yml  
        secrets: inherit
    dependency_scan:
         uses: ./.github/workflows/dependency_scan.yml  
    docker_file_scan:
         uses: ./.github/workflows/docker_file_scan.yml 
    build:
         needs: [code-quality_scan,secrets_scan,dependency_scan,docker_file_scan] 
         uses: ./.github/workflows/docker_build_push.yml
         secrets: inherit 

    trivy:
        needs: [build]
        uses: ./.github/workflows/trivy_image_scan.yml
        secrets: inherit 

     #CD
     
    deploy_app:
        needs: [trivy]
        uses: ./.github/workflows/deploy_server.yml
        secrets: inherit